export { default as locations } from "./src/locations.js"
export { default as consultationStatuses } from "./src/consultation-statuses.js"
export { default as consultationLocations } from "./src/consultation-locations.js"
export * from "./src/apis.js"
export * from "./src/required-fields.js"
